deprecated

diff --git a/.devcontainer/custom_component_helper b/.devcontainer/custom_component_helper
--- a/.devcontainer/custom_component_helper
+++ b/.devcontainer/custom_component_helper
@@ -4,7 +4,7 @@ function StartHomeAssistant {
   mkdir /config
 
   echo "Copy configuration.yaml"
-  cp -f .devcontainer/secrets.yaml /config/ || echo ".devcontainer/secrets.yaml are missing!" exit 1
+  cp -f .devcontainer/configuration.yaml /config/ || echo ".devcontainer/configuration.yaml are missing!" exit 1
 
   echo "Copy the custom component"
   rm -R /config/custom_components/ || echo ""
